### ISSUE TITLE
umap properties like iconUrl are not adopted

### ISSUE THREAD

**Issue by ABJ-Samuel** [hholzgra/maposmatic#123]
I am trying to render a map with a marker from umap but the iconUrl get not adopted

**Comment by hartmut-mariadb** [comment]
Can you share the umap file, or give me the number or URL of the map render request you tried?

**Comment by hartmut-mariadb** [comment]
Looks as if Umap extended (or just changed) their icon set.

They are using local file paths instead of a "proper" file:// URL for the Icons you can pick from their UI, in your case:

"iconUrl": "/uploads/pictogram/alcohol-24_PpEAcC1.png"

I have a regular expression in place that will find such "/uploads/pictogram/" references and rewrite them to use local SVG icons on my server instead, but I only have a SVG icon for "alcohol-shop", not for "alcohol".

Need to see how to get things in sync again ...

**Comment by ABJ-Samuel** [comment]
Perfect thank you,
With umap you can also enter a number instead of images, for example.

Unfortunately, this will not be adopted either.

My original problem is that I would like to number the markers

**Comment by hartmut-mariadb** [comment]
> With umap you can also enter a number instead of images

that seems to be a new feature available on the original `.fr` instance, but not the `.de` one yet, so I wasn't even aware of that. Need to figure out how this is actually stored in the exported save file ... I'll probably create a separate issue for that ...

**Comment by hartmut-mariadb** [comment]
Both the .fr and .de icon schemes should now work, and short text labels, too

**Comment by hartmut-mariadb** [comment]
mostly fixed now, "icon from text" only works with Unicode Basic Multilingual Plane characters though, not with anything from the extended planes. So ☃ works, but 😃 does not and gets rendered as ������ instead ...

**Comment by hholzgra** [comment]
Created new issue #135 for the unicode extended planes problem, everything else should be fixed so closing this one
