### ISSUE TITLE
Services get stuck after purging old render jobs

### ISSUE THREAD

**Issue by hartmut-mariadb** [hholzgra/maposmatic#131]
After the RENDERING_RESULT_MAX_SIZE_GB threshold is reached and oldest rendering results are purged the render services are just sitting around idle, not processing any further pending jobs.

Not sure what is causing this, it might be a race condition between the multiple service queues now running in parallel, and may simply not have been hit as I did some disk cleanup and was able to dedicate more disk space to rendered results at about the same time I added the multi-queue feature, so that there had simply not been any purge runs until now.

For now I have just bumped up the max. storage size again as I don't have the time to investigate, this should serve as a viable workaround for another few months, even though I hope I get to finding the root cause much earlier than that.

**Comment by hholzgra** [comment]
The actual problem was that thumbnail and error log files, which are not purged, where not properly ignored during the file scan, so the list of files to process got longer and longer over time even though in the end these files would not get removed anyway.

This lead to a six to seven minute delay after each render job every time the disk usage threshold was exceeded and file purge initiated.

With the files known to remain properly ignored during scanning each purge run only takes a few seconds again as expected.
