### ISSUE TITLE
House numbers on the map

### ISSUE THREAD

**Issue by dimmer123** [hholzgra/maposmatic#46]
Hi, I need help. I installed maposmatic-vagrant. Now I am trying to print a map with house numbers. I changed zoom level in openstreetmap-carto/addressing.mss, but still I get house numbers only if I select a small piece of the town like 1x1km. When I select the area 6x7km house numbers disappear (.

**Comment by hholzgra** [comment]
The problem with housenumbers in all the standard styles is that the easily overlap with house outlines on the lower zoom levels, and in that case the house outline has priority.

I had recently added an extra housenumber overlay due to this, but this is not installed on the new server instance yet (as sudden hardware problems on the old server forced me to switch over before all minor migration issues were sorted out).

The Housenumber overlay, which renders numbers unconditionally unless they overlap with other housenumbers, should re-appear within the next day or two ...

**Comment by dimmer123** [comment]
Thank you!
