### ISSUE TITLE
OSM Update ?

### ISSUE THREAD

**Issue by vinber** [hholzgra/maposmatic#51]
Hi,
there's no update since 3 week ?
Can we make something, help for storage ?

**Comment by hholzgra** [comment]
User/admin error. I had disabled the minutely update SystemD timers during some maintenance I did earlier this month, and then forgot to enable them again. As I so far only get notified when the timer scripts actually return an error -- which they can't when not running at all -- I did not spot this.

Keeping this issue open until I have improved monitoring / notifications to cover this ...

**Comment by hholzgra** [comment]
I only activated the main OSM database diff import again for now, this may take more than a day to catch up with the three weeks of diffs that have piled up since then.

Once that has finished I will also enable diff import for the WayMarkedTrails overlay layers, which will then also take more than a day or so to catch up again.

Progress can be watched here: https://print-test.get-map.org/munin/localdomain/localhost.localdomain/osm_lag.html

**Comment by hholzgra** [comment]
4 1/2 hours in, and lag was only reduced by ~10% so far. So "more than a day" will rather be close to two days before the main database is fully up to date again ...
