### ISSUE TITLE
Unable to find SVG maps

### ISSUE THREAD

**Issue by matkoniecz** [hholzgra/maposmatic#52]
Main site has "The generated maps are available in PNG, PDF and SVG formats" but I see o way to generate SVG maps.

No map style is marked as SVG, all seems to be PNG

**Comment by matkoniecz** [comment]
oh. I was confused how SVG maps are supposed to be generated from PNG, but I guess that it applies map style to a different process.

Added to https://wiki.openstreetmap.org/wiki/SVG#Ways_to_create_an_SVG_map_from_OpenStreetMap (so my program will be at beast first to generate SVG from OSM **locally** in web browser. Maybe with distinction of making relatively easy to setup own map styles. Congratulations on being first to offer SVG rendering from within browser!)

**Comment by hholzgra** [comment]
Actually every solution that uses the Mapnik library to render OSM data can generate any of the output formats supported by Mapnik easily for any map style. There is nothing output format specific in the map stylesheets themselves (although those that provide SVG point/marker symbols create better vector format quality results).

Mapnik again basically supports everything that either of the two underlying graphics libraries support. For the AGG render library that is just high quality PNG, for the Cairo Graphics render library backend that's various bitmap and vector formats.

PNG output from the Cairo Graphics backend is only slightly less good than the AGG output, usually the difference is barely noticeable, but it comes at the advantage that you can combine Mapnik output with your own graphics, e.g. when using the Mapnik Python bindings together with PyCairo. This is the approach that MapOSMatic uses to add things like the page title, the side index, the copyright annotations, and even some of the overlay styles that would not easily be possible with Mapnik, like the "Surveilance under Surveilance" overlay with its camera coverage arcs.

The orignal MapOSMatic developers chose to render PNG, PDF and SVGz. PostScript would also be possible, but it's rather obsolete these days. I chose to offer additional bitmap formats, but instead of having Mapnik render them I just let it render high quality 32bit PNG, and then use other external tools to convert that output into 8bit PNG and JPG formats.

One disadvantage of the Cairo Graphics based SVG output is that Cairo does not support grouping objects into InkScape-compatible layers. So the resulting SVG output is fine for actual on-screen or on-paper rendering, but it is not really suitable for using InkScape or other vector oriented graphics programs to post-edit the automatic render results.

There was a project to add direct/native SVG output as a third render backend to Mapnik, but this unfortunately never got finished. So taking the Cairo Graphics route is still the least worse approach to generating SVG from OSM data as of now ...
